# Generated by Django 5.2.6 on 2025-09-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
    ]
